sudo: false
language: node_js
node_js:
  - 'stable'
env:
  global:
    - BUILD_TIMEOUT=10000
services:
  - mongodb
install:
  - npm install
  - npm install cypress
# before_script:
#   - sleep 15
#   - mongo sapeur --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
